#settings pertaining to the trigger configuration
trigger: 
  #this is the trigger input used to generate
  #level 0, i.e. sampling on the inputs
  #options: 
  #'nim', which is a -700mV signal on "TI" nim input
  #'self', trigger on a threshold on the inputs (FIR trigger), and activate the self-trigger settings
  #'both', is an or between nim and self
  level0_input: 'nim'
  #these settings only active if level0_input = 'self'
  self_trig_settings:
    pulse_polarity: 'n' #'n' or 'p', determines if threshold is negative or positive
    #indexed by card number 
    enabled_channels: 
      0: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    pe_for_trigger: 0.1 #how many PE needed for a trigger
    pe_to_adc: 
      0: [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150]
    #will have to restructure code to do multi-card coinc combinatorix
    coinc_enable: 1
    min_coinc_channels: 3 #>= this number of channels will generate a trigger
  
  #two LEMO outputs are available: 'to' and 'uo'.
  #They are highly configurable, see manual pages 120 and 121. 
  #Default value is empty list, which will have nothing output on these channels.
  #Options (put multiple in a list): 
  #'coinc', if a coincidence trigger is generated
  #'sum', sum-or of all channels enabled in self trigger
  #'ext', external trigger to ADC FPGA rerouted to output
  to_settings: ['ext']
  #Options (put multiple in a list): 
  #'busy', if sample logic is busy
  #'ready', if sample logic is ready
  uo_settings: ['busy']

run:
  duration_per_file: 50 #seconds
  file_suffix: "cryotest"
  card_numbers: [0] #[0, 1, 2] with  matching IP's below
  card_ips: ['192.168.4.40']

digitization:
  clock: 2 #0: 250MHz, 1: 125MHz, 2=62.5MHz 3: 25 MHz
  gain: 1 #default = 1, 1 = 2V; 0 = 5V, 2 and 3 = 1.9V
  termination: 1 #1 = 50 ohm, 0 = 1kohm

