run:
  duration_per_file: 2 #seconds
  spill_duration: 0.5 #seconds between subsequent read/write thread initiations, and swapping between memory banks 
  do_loop: False #loop mode described here please
  hours_per_iteration: 10 #for loop mode 
  file_suffix: "evantest"
  card_numbers: [0,1,2] #[0, 1, 2] with  matching IP's below; Primary card must always be "0" 
  card_ips: ['192.168.4.40', '192.168.4.100', "192.168.4.102"]
  debug: 1 #will execute additional print statements (from NGMModule::getDebug())

#the clock I beleive technically can be different for each card,
#but for the moment I am keeping it universal as it is "shared" on
#LVDS for all connected cards by default. 
clock: 3 #0: 250MHz, 1: 125MHz, 2=62.5MHz 3: 25 MHz

#a certain set of instructions is executed if the
#memory on any card exceeds this fraction of being full. 
full_fraction: 0.9

#settings for card 0, comments removed for later cards
0:
  #settings pertaining to the trigger configuration
  trigger: 
    #this is the trigger input used to generate
    #level 0, i.e. sampling on the inputs
    #options: 
    #'nim', which is a -700mV signal on "TI" nim input, sets enable external trigger bit to 1
    #'self', specifically sets external trig enable to 0, relying only on FIR trigger settings
    level0_input: ['nim']
    #these settings only active if level0_input = 'self'
    self_trig_settings:
      #indexed by card number 
      #this enables internal trigger on these channels,
      #and includes them in the coinc settings if coinc is enabled. 
      #if none are listed, or the card is not listed, then internal trig is disabled. 
      enabled_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
      pe_for_trigger: 10 #how many PE needed for a trigger
      pe_to_adc: [150, 150,150,150,150,150,150,150,150,150,150,150,150,150,150,150] #note, this is in ADC counts which changes the mV conversion depending on gain = 1 or 0!. 
      #will have to restructure code to do multi-card coinc combinatorix
      coinc_enable: 0
      min_coinc_channels: 3 #>= this number of channels will generate a trigger
    
    #two LEMO outputs are available: 'to' and 'uo'.
    #They are highly configurable, see manual pages 120 and 121. 
    #Default value is empty list, which will have nothing output on these channels.
    #Options (put multiple in a list): 
    #'coinc', if a coincidence trigger is generated for combos of channels in table 1
    #'sum', sum-or of all channels enabled in self trigger
    #'ext', external trigger to ADC FPGA rerouted to output
    to_settings: []
    #Options (put multiple in a list): 
    #'busy', if sample logic is busy
    #'ready', if sample logic is ready
    #'coinc', coincidences for combos of channels in table 2  
    uo_settings: ['busy']

  
  digitization:
    
    gain: 1 #default = 1, 1 = 2V; 0 = 5V; 2V range is 0.03 ADC/mV, 5V range is 0.076 ADC/mV 
    termination: 1 #1 = 50 ohm, 0 = 1kohm
    #applies an inverting amplifier to the input. also affects trigger. the trigger works off
    #of a positive polarity signal, so if your signals are negative polar, set invert = 1
    invert: 1 

    #for these digitization settings, look to page 60 of the manual. 
    pretrig_delay: 50 #time shift in the adc signal relative to the input, for generating triggers and phasing accumulators
    raw_data_start_index: 0 #the number of samples after the internal trigger generation for which to start digitizing. if you are unsure, set to 0
    raw_data_sample_length: 50 #how many samples are saved to stored data, starts from baseline index. 
    gate_window_length: 60000 #how many clocks it takes from internal trigger generation until that channel is "ready" again. 

    #dac_offset: see page 113: a calc is made in the run script based on the gain setting. 
    #for example, parametrized here: 
    #0 is centered in the full ADC range, -1V to +1V
    #-1 is fully shifted negative polar, -2V to 0V
    #1 is fully shifted positive, 0V to 2V. 
    #all floats in between are allowed. default will floor or ceiling if outside of -1 to 1
    dac_offset: 0 


1:
  trigger: 
    level0_input: ['nim']
    self_trig_settings: 
      enabled_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
      pe_for_trigger: 10 #how many PE needed for a trigger
      pe_to_adc: [150, 150,150,150,150,150,150,150,150,150,150,150,150,150,150,150] #note, this is in ADC counts which changes the mV conversion depending on gain = 1 or 0!. 
      coinc_enable: 0
      min_coinc_channels: 3 #>= this number of channels will generate a trigger
    
    
    to_settings: ['coinc', 'sum']
    uo_settings: ['busy']

  
  digitization:
    
    gain: 1 #default = 1, 1 = 2V; 0 = 5V; 2V range is 0.03 ADC/mV, 5V range is 0.076 ADC/mV 
    termination: 1 #1 = 50 ohm, 0 = 1kohm
    invert: 1 

    #for these digitization settings, look to page 60 of the manual. 
    pretrig_delay: 50 #time shift in the adc signal relative to the input, for generating triggers and phasing accumulators
    raw_data_start_index: 0 #the number of samples after the internal trigger generation for which to start digitizing. if you are unsure, set to 0
    raw_data_sample_length: 50 #how many samples are saved to stored data, starts from baseline index. 
    gate_window_length: 6000 #how many clocks it takes from internal trigger generation until that channel is "ready" again. 

    dac_offset: 0 


2:
  trigger: 
    level0_input: ['nim']
    self_trig_settings: 
      enabled_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
      pe_for_trigger: 10 #how many PE needed for a trigger
      pe_to_adc: [150, 150,150,150,150,150,150,150,150,150,150,150,150,150,150,150] #note, this is in ADC counts which changes the mV conversion depending on gain = 1 or 0!. 
      coinc_enable: 0
      min_coinc_channels: 3 #>= this number of channels will generate a trigger
    
    
    to_settings: ['coinc', 'sum']
    uo_settings: ['busy']

  
  digitization:
    
    gain: 1 #default = 1, 1 = 2V; 0 = 5V; 2V range is 0.03 ADC/mV, 5V range is 0.076 ADC/mV 
    termination: 1 #1 = 50 ohm, 0 = 1kohm
    invert: 1 
    
    #for these digitization settings, look to page 60 of the manual. 
    pretrig_delay: 50 #time shift in the adc signal relative to the input, for generating triggers and phasing accumulators
    raw_data_start_index: 0 #the number of samples after the internal trigger generation for which to start digitizing. if you are unsure, set to 0
    raw_data_sample_length: 50 #how many samples are saved to stored data, starts from baseline index. 
    gate_window_length: 6000 #how many clocks it takes from internal trigger generation until that channel is "ready" again. 

    dac_offset: 0 